---
name: Daily Build at 10 AM UTC

on:
  schedule:
    - cron: "0 10 * * *" # Run daily at 10 AM UTC
  push:
    branches:
      - main
jobs:
  debian_latest:
    uses: ./.github/workflows/build-template.yml
    with:
      os: debian
      os_version: latest

  debian_12_slim:
    uses: ./.github/workflows/build-template.yml
    with:
      os: debian
      os_version: 12-slim

  debian_12:
    uses: ./.github/workflows/build-template.yml
    with:
      os: debian
      os_version: 12

  ubuntu_24_04:
    uses: ./.github/workflows/build-template.yml
    with:
      os: ubuntu
      os_version: 24.04

  ubuntu_22_04:
    uses: ./.github/workflows/build-template.yml
    with:
      os: ubuntu
      os_version: 22.04

  ubuntu_latest:
    uses: ./.github/workflows/build-template.yml
    with:
      os: ubuntu
      os_version: latest
